fix workflow

diff --git a/.github/workflows/check-pr.yml b/.github/workflows/check-pr.yml
--- a/.github/workflows/check-pr.yml
+++ b/.github/workflows/check-pr.yml
@@ -1,47 +1,56 @@
-# Validate that a PR only changed files in the ceremonies directory
-name: Check Ceremony
+# check that a PR modified the correct files and nothing more
+name: Check PR Files
 
-# runs on PRs
 on:
-  pull_request
+  pull_request:
+    branches:
+      - dev
+    paths:
+      - 'ceremonies/**'
 
 jobs:
-  check:
+  check-files:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-    # we want to check that the correct files were added
-    # also check that no more than three files were added
-    - name: Check directory and files
-      run: |
-        changed_files=$(git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
-        for file in $changed_files; do
-          if [[ $file == ceremonies/* ]]; then
-            project_name=${file#ceremonies/}
-            project_name=${project_name%%/*}
-            if [[ ! -d "ceremonies/$project_name" ]]; then
-              echo "Directory ceremonies/$project_name does not exist"
-              exit 1
-            fi
-            if [[ ! -f "ceremonies/$project_name/$project_name.r1cs" ]]; then
-              echo "File ceremonies/$project_name/$project_name.r1cs does not exist"
-              exit 1
-            fi
-            if [[ ! -f "ceremonies/$project_name/$project_name.wasm" ]]; then
-              echo "File ceremonies/$project_name/$project_name.wasm does not exist"
-              exit 1
-            fi
-            if [[ ! -f "ceremonies/$project_name/p0tionConfig.json" ]]; then
-              echo "File ceremonies/$project_name/p0tionConfig.json does not exist"
-              exit 1
-            fi
-            file_count=$(ls ceremonies/$project_name | wc -l)
-            if [[ $file_count -ne 3 ]]; then
-              echo "Unexpected files in ceremonies/$project_name"
-              exit 1
-            fi
+      - name: Get PR number
+        run: echo "PR_NUMBER=$(jq --raw-output .number $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
+
+      - name: Get changed files
+        id: get-changed-files
+        uses: jitterbit/get-changed-files@v1
+        with:
+          format: 'csv'
+
+      - name: Validate files
+        run: |
+          changed_files="${{ steps.get-changed-files.outputs.all }}"
+          IFS=', ' read -r -a files <<< "$changed_files"
+          
+          if [[ ${#files[@]} -ne 3 ]]; then
+            echo "More than 3 files have been changed"
+            exit 1
           fi
-        done
+
+          r1cs_files=($(grep -E '\.r1cs$' <<< "${files[@]}"))
+          wasm_files=($(grep -E '\.wasm$' <<< "${files[@]}"))
+          json_files=($(grep -E 'p0tionConfig\.json$' <<< "${files[@]}"))
+
+          if [[ ${#r1cs_files[@]} -ne 1 || ${#wasm_files[@]} -ne 1 || ${#json_files[@]} -ne 1 ]]; then
+            echo "Invalid or missing file extensions"
+            exit 1
+          fi
+
+          directory_name="ceremonies/$(echo $GITHUB_HEAD_REF | sed -r 's/-ceremony$//')"
+
+          for file in "${files[@]}"; do
+            if [[ ! $file =~ ^$directory_name/ ]]; then
+              echo "Files must be inside the $directory_name directory"
+              exit 1
+            fi
+          done
+
+          echo "All checks passed"
